In [3]:
import numpy as np
import tensorflow as tf

# 예제 7.2 시퀀스 예측 데이터 생성
X = []
Y = []

for i in range(6):
  # [0, 1, 2, 3], [1, 2, 3, 4] 같은 정수의 시퀀스를 만듭니다.
  lst = list(range(i, i + 4))

  # 위에서 구한 시퀀스의 숫자들을 각각 10으로 나눈 다음 저장합니다.
  # SimpleRNN에 각 타임스텝에 하나씩 숫자가 들어가기 때문에 여기서도 하나씩 분리해서 배열에 저장합니다.
  X.append(list(map(lambda c: [c / 10], lst)))

  # 정답에 해당하는 4, 5 등의 정수 역시 앞에서처럼 10으로 나눠서 저장합니다.
  Y.append((i + 4) / 10)

X = np.array(X)
Y = np.array(Y)
for i in range(len(X)):
  print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [5]:
# 예제 7.3 : 시퀀스 예측 모델 정의
# input_shape = [timesteps, input_dim]
# timesteps : 순환 신경망이 입력에 대해 계산을 반복하는 횟수
# input_dim : 입력 벡터의 크기
model = tf.keras.Sequential([
                             tf.keras.layers.SimpleRNN(units = 10, return_sequences = False, input_shape = [4, 1]),
                             tf.keras.layers.Dense(1)
])

model.compile(optimizer = 'adam', loss = 'mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 예제 7.4 : 네트워크 훈련 및 결과 확인
# verbose = 0 : 훈련 과정에서의 출력을 나오지 않게 합니다.
model.fit(X, Y, epochs = 100, verbose = 0)

print(model.predict(X))

[[0.35158154]
 [0.5227035 ]
 [0.6540485 ]
 [0.7438684 ]
 [0.79712695]
 [0.8216642 ]]


In [9]:
# 예제 7.5 : 학습되지 않은 시퀀스에 대한 예측 결과
print(model.predict(np.array([[[0.6], [0.7], [0.8], [0.9]]])))
print(model.predict(np.array([[[-0.1], [0.0], [0.1], [0.2]]])))

[[0.82552844]]
[[0.15233523]]
