In [0]:
import tensorflow as tf
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [0]:
# 예제 3.23 : 세 번째 신경망 네트워크 - XOR
import numpy as np

x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])
w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
  error_sum = 0

  for j in range(4):
    output = sigmoid(np.sum(x[j] * w) + b * b_x)
    error = y[j] - output
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error
    error_sum += error

  if i % 200 == 199:
    print(i, error_sum)

199 [-0.00155531]
399 [-6.32298636e-05]
599 [-2.57155198e-06]
799 [-1.30299474e-07]
999 [3.72284215e-09]
1199 [3.72284215e-09]
1399 [3.72284215e-09]
1599 [3.72284215e-09]
1799 [3.72284215e-09]
1999 [3.72284215e-09]


In [0]:
# 에제 3.24 : XOR 네트워크의 평가
for i in range(4):
  print('X :', x[i], 'Y :', y[j], 'Output :', sigmoid(np.sum(x[i] * w) + b))

X : [1 1] Y : [0] Output : 0.5128176286712095
X : [1 0] Y : [0] Output : 0.5128176305326305
X : [0 1] Y : [0] Output : 0.4999999990686774
X : [0 0] Y : [0] Output : 0.5000000009313226


In [0]:
# 예제 3.25 : XOR 네트워크의 w, b 값 확인
print('w :', w)
print('b :', b)

w : tf.Tensor([ 5.1281754e-02 -7.4505806e-09], shape=(2,), dtype=float32)
b : tf.Tensor([3.7252903e-09], shape=(1,), dtype=float32)


In [0]:
# 예제 3.27 : tf.keras를 이용한 XOR 네트워크 계산
import numpy as np
x = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
y = np.array([[0], [1], [1], [0]])

model = tf.keras.Sequential([
                             tf.keras.layers.Dense(units = 2, activation = 'sigmoid', input_shape = (2, )),
                             tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

model.compile(optimizer = tf.keras.optimizers.SGD(lr = 0.1), loss = 'mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [0]:
# 예제 3.28 : tf.keras를 이용한 2-레이어 XOR 네트워크 학습
history = model.fit(x, y, epochs = 2000, batch_size = 1)

In [0]:
# 예제 3.29 : tf.keras를 이용한 2-레이어 XOR 네트워크 평가
model.predict(x)

array([[0.12440106],
       [0.8501781 ],
       [0.8606547 ],
       [0.14353931]], dtype=float32)

In [0]:
# 예제 3.30 : 2-레이어 XOR 네트워크의 가중치와 편향 확인
for weight in model.weights:
  print(weight)

<tf.Variable 'dense_2/kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[-4.4572587, -3.958479 ],
       [ 4.6040115,  3.7387128]], dtype=float32)>
<tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([ 2.3944108, -2.0710657], dtype=float32)>
<tf.Variable 'dense_3/kernel:0' shape=(2, 1) dtype=float32, numpy=
array([[-5.1362967],
       [ 5.527945 ]], dtype=float32)>
<tf.Variable 'dense_3/bias:0' shape=(1,) dtype=float32, numpy=array([2.301899], dtype=float32)>
