In [7]:
import tensorflow as tf
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

# 예제 3.15 : True, False의 정숫값 확인
print(int(True))
print(int(False))

1
0


In [9]:
# 예제 3.16 : 첫 번째 신경망 네트워크 - AND
import numpy as np
x = np.array([[1, 1], [0, 1], [1, 0], [0, 0]])
y = np.array([[1], [0], [0], [0]])
w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1

for i in range(2000):
  error_sum = 0
  for j in range(4):
    output = sigmoid(np.sum(x[j] * w) + b_x * b)
    error = y[j][0] - output
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error
    error_sum += error

  if i % 200 == 199:
    print(i, error_sum)

199 -0.0920020329709049
399 -0.058741208620198486
599 -0.043005096248944996
799 -0.03383158177477863
999 -0.027839302498523212
1199 -0.023626112921577503
1399 -0.020506268752892003
1599 -0.01810635039783834
1799 -0.0162044313989012
1999 -0.014660298816007847


In [11]:
# 예제 3.17 : 파이썬에서 리스트에 정수를 곱하기
print([1, 2, 3] * 2)
print([1, 2, 3] * 0)
print([1, 2, 3] * -1)

[1, 2, 3, 1, 2, 3]
[]
[]


In [12]:
# 예제 3.18 : 파이썬에서 리스트에 실수를 곱하기
print([1, 2, 3] * 0.01)

TypeError: ignored

In [14]:
# 예제 3.19 : 넘파이 Array에 정수 및 실수 곱하기
import numpy as np
print(np.array([1, 2, 3]) * 2)
print(np.array([1, 2, 3]) * 0)
print(np.array([1, 2, 3]) * -1)
print(np.array([1, 2, 3]) * 0.01)

[2 4 6]
[0 0 0]
[-1 -2 -3]
[0.01 0.02 0.03]


In [15]:
# 예제 3.20 : AND 네트워크의 평가
for i in range(4):
  print('X :', x[i], 'Y :', y[i], 'Output :', sigmoid(np.sum(x[i] * w) + b))

X : [1 1] Y : [1] Output : 0.9657786841873902
X : [0 1] Y : [0] Output : 0.02425653133737452
X : [1 0] Y : [0] Output : 0.02432893368022068
X : [0 0] Y : [0] Output : 2.1964546554559882e-05
